### ISSUE TITLE
Bug: App crashes when Chuubot hiccups

### ISSUE THREAD

**Issue by Ryxias** [Ryxias/react-hell#42]
# Description
Occasionally Chuubot will receive a weird message that causes the entire website to crash.

```
{"reply_to":1,"type":"message","channel":"C5U5C723Z","user":"U6X5J5TDX","text":"The game has already started... [0022QOQSMMPS]","ts":"1506582972.000132"}
/home/ryxias/repos/react-hell/lib/slackbot_framework.js:134
      return null !== message_text.match(this.regex);
                                  ^

TypeError: Cannot read property 'match' of undefined
    at ChuubotListenerRegexp.matches (/home/ryxias/repos/react-hell/lib/slackbot_framework.js:134:35)
    at listeners.forEach (/home/ryxias/repos/react-hell/lib/slackbot_framework.js:51:24)
    at Array.forEach (native)
    at RTMClient.Chuubot.rtm.on (/home/ryxias/repos/react-hell/lib/slackbot_framework.js:49:24)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/eventemitter3/index.js:116:35)
    at RTMClient.emit (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/client.js:82:39)
    at RTMClient._handleWsMessageViaEventHandler (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:471:10)  
    at RTMClient.handleWsMessage (/home/ryxias/repos/react-hell/node_modules/@slack/client/lib/clients/rtm/client.js:425:10)
    at WebSocket.wrapper (/home/ryxias/repos/react-hell/node_modules/lodash/lodash.js:4968:19)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:841:10)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:536:18
    at Receiver.applyExtensions (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:371:5)
    at /home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/home/ryxias/repos/react-hell/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/home/ryxias/repos/react-hell/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
[nodemon] app crashed - waiting for file changes before starting...
```

# Objective

First thing's first, we want to find this bug in Chuubot and fix it. 

Second, if Chuubot crashes **it should not take down the entire site with it**.  It should error, log it somewhere, then gracefully recover.

**Comment by Ryxias** [comment]
I split chuubot off of the rest of the website a few PRs ago: https://github.com/Ryxias/react-hell/pull/48
