### ISSUE TITLE
Bug: App Crashes on Sequelize validation error

### ISSUE THREAD

**Issue by Ryxias** [Ryxias/react-hell#43]
# Description

Very unclear what's going on but this happens more often than I'm happy with

```
Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/ryxias/repos/react-hell/node_modules/sequelize/lib/dialects/mysql/query.js:201:16)
    at Query.connection.query [as onResult] (/home/ryxias/repos/react-hell/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)

Unhandled rejection SequelizeUniqueConstraintError: Validation error
    at Query.formatError (/home/ryxias/repos/react-hell/node_modules/sequelize/lib/dialects/mysql/query.js:201:16)
    at Query.connection.query [as onResult] (/home/ryxias/repos/react-hell/node_modules/sequelize/lib/dialects/mysql/query.js:55:23)
    at Query.Command.execute (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:515:28)
    at PacketParser.onPacket (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:94:16)
    at PacketParser.executeStart (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/home/ryxias/repos/react-hell/node_modules/mysql2/lib/connection.js:102:29)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)


```

**Comment by Ryxias** [comment]
The cause of this is due to the `UNIQUE INDEX`'s on `slack_messages`.  The `user-created` index makes it so if the same person types a message within 1 second, it will violate the unique key constraint.  The `text-created` index makes it so that if the same message is typed twice in 1 second, it will violate the key constraint.

**Comment by Ryxias** [comment]
The solution is to remove the unique part of the index.  I can understand the motivation, but it's not necessary.

Additionally, I don't know why the `text-created` key is *unique*.  It does not have to be.
